### ISSUE TITLE
[Quest] Identificar subsistemas 

### ISSUE THREAD

**Issue by MariaMilena** [marcosdosea/QueroJobs#101]
💻 **O que pode ser adicionado?**
... Identificar subsistemas externos que precisará se comunicar com a aplicação

E após identificas criar issue para implementar os subsistemas do Design Model

**Comment by joannestephany** [comment]
API para aceitar pagamento via cartão.
No caso de pagamento dos nossos planos

**Comment by joannestephany** [comment]
API para localizar e preencher os dados da empresa ao informar o CNPJ

**Comment by MariaMilena** [comment]
Busca CEP

**Comment by Kendy619** [comment]
API para gerar NFE.
