### ISSUE TITLE
[Feat] Implements use case ManterVaga

### ISSUE THREAD

**Issue by MariaMilena** [marcosdosea/QueroJobs#143]
💻 **O que pode ser adicionado?**
Implements a Vacancy CRUD
Implements a Vacancy VM

**Comment by joannestephany** [comment]
- [ ] 1) Core Project
-(Houve alteração banco? =>)Rodar o comando de extração com todas as entidades
-Pasta Services dentro de Core criar a classe IXXXServices.cs que implementará todos os métodos que a classe de uso usurá

- [ ] 2) Vai para o projeto Service
-Implementa o service criado anteriormente(implementa a interface).

- [ ] 3) QueroJobsWeb Project
-Em "Program.cs" Fazer a injeção de dependência, seguindo o padrão das linhas 13...17
-Pasta Mappers -> Cria uma entidade profile XXXXProfile.cs e seguir o modelo já existente

- [ ] 4) Em Models
-Cria um método da sua entidade XXXXModel
-Pega os atributos da Entity.cs (Candidate.cs) que estão no Core e joga na Model criada.
-Implementa as restrições com base no banco de dados (se basear no CompanyModel)

- [ ] 5) Em Controllers cria um XXXXController.cs (CompanyController.cs) e implementar a injeção de banco (seguir o modelo do Company) (Mapper)
-Implementar as páginas no Controller.


5) Em Views
-Criar pasta da entidade (Ex:Company) e criar um index
-Copiar o conteúdo do index.cshtml do Company e colar, adaptando, quando necessário.
