### ISSUE TITLE
[Feat] Criar protótipos responsivos

### ISSUE THREAD

**Issue by joannestephany** [marcosdosea/QueroJobs#206]
💻 **O que pode ser adicionado?**
Adicionar protótipos versão mobile 

👾 **Qual impacto teria no projeto?**
Viabiliza a implementação de responsividade

💡 **Possíveis alternativas:**
Entrega incremental

👌 **Checklist do que já foi feito:**
- [x] TELA CADASTRO PESSOA FISICA
- [x] TELA CADASTRO PESSOA JURIDICA
- [x] TELA CURRICULO

**Comment by joannestephany** [comment]
Por solicitação de @MariaMilena pretendo entregar inicialmente o que já está sendo desenvolvido para dar continuidade ao trabalho. Agradeço se deixar por escrito quais telas tem prioridade imediata.

**Comment by Ericles-Porty** [comment]
Tela de currículo
