### ISSUE TITLE
Implementar a tela dos casos de uso da empresa gerenciadora.

### ISSUE THREAD

**Issue by Ericles-Porty** [marcosdosea/QueroJobs#49]
Criar a tela única no FIGMA.
Criar collaboration para todos. (Basta criar para um caso de uso e replicar para os outros)

**Comment by joannestephany** [comment]
Preciso de mais expecificações, se possível solicito uma reunião rápid para alinhar pensamentos.

**Comment by MariaMilena** [comment]
Okay, Joanne.
